//
//  DataHelpers.swift
//  TerminalAPIKit
//
//  Copyright (c) 2022 Adyen N.V.
//

import Foundation

internal extension Data {
    
    /// Creates a new data buffer with securely generated random bytes.
    ///
    /// - Parameter count: The number of randomly generated bytes.
    init?(secureRandomBytesWithCount count: Int) {
        self.init(count: count)
        
        let result = withUnsafeMutableBytes { bytes -> OSStatus in
            guard let baseAddress = bytes.baseAddress else {
                return errSecAllocate
            }
            
            return SecRandomCopyBytes(kSecRandomDefault, count, baseAddress)
        }
        
        if result != errSecSuccess {
            return nil
        }
    }
    
    /// Performs a bitwise XOR operation on the bytes of the two given data buffers.
    /// The two data buffers must be of the same size.
    ///
    /// - Parameters:
    ///   - lhs: The first data buffer to XOR.
    ///   - rhs: The second data buffer to XOR.
    static func ^(lhs: Data, rhs: Data) -> Data {
        assert(lhs.count == rhs.count, "Data buffers must have an equal size.")
        
        let result = zip(lhs, rhs).map(^)
        
        return Data(result)
    }
    
}
